<a href="https://colab.research.google.com/github/istrate-mihai/CakePHP-PatientCare-App/blob/main/ML4D2E%3B_07%3B_Matrices_and_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working with Data

## Understanding scalar and vector operations

In [1]:
import numpy as np

In [43]:
# myInt = np.short(15)
# print(myInt)
# myArray = np.arange(1, 11, 2)
# myArray
# oneList = np.ones(4, dtype=np.int16)
# oneList + 1
# myCountList = np.array([1, 2, 3, 4])
# myCountList + 1
# 2 ** myCountList
# a = np.array([True, False, True, False])
# b = np.array([True, True, False, False])
# np.logical_and(a, b)
# np.logical_or(a, b)
# np.logical_not(a, b)
# np.logical_xor(a, b)
# myVect = np.array([1, 2, 3, 4], dtype=np.int16)
# myVect * myVect
# np.multiply(myVect, myVect)
# myVect.dot(myVect)
# A = np.array([[1, 1], [1, 0]])
# B = np.array([[1, 0], [0, 1]])
# C = A - B
# C * 2
# y = Xb

# X = np.array(
#       [
#         [4, 5],
#         [2, 4],
#         [3, 3]
#       ]
#     )

# b = [3, -2]

# print(X @ b)

# sum([4*3, 5*-2]) # = 2
# sum([2*3, 4*-2]) # = -2
# sum([3*3, 3*-2]) # = 3

# B = np.array(
#       [
#         [3, -2],
#         [-2, 5]
#       ]
#     )

# print(X @ B)

#A = np.array([[1, 2, 3], [2, 3, 5], [7, 11, 13]])
#A

In [32]:
# A.transpose()

array([[ 1,  2,  7],
       [ 2,  3, 11],
       [ 3,  5, 13]])

In [44]:
# np.linalg.inv(A)

# B = np.array([[1, 2, 3], [-1, 0, -1], [3, 4, 7]])
# np.linalg.inv(B)

In [45]:
# myVect = np.array(np.int16([1, 2, 3, 4]))

# print(myVect + 1)
# print(myVect - 1)
# print(2 ** myVect)

In [50]:
A = np.arange(1, 100, 3)
A.reshape(11, 3)

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43],
       [46, 49, 52],
       [55, 58, 61],
       [64, 67, 70],
       [73, 76, 79],
       [82, 85, 88],
       [91, 94, 97]])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

print(a == b)
print(a < b)

[False  True False  True]
[ True False  True False]


In [ ]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(np.logical_not(a))
print(np.logical_xor(a, b))

[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]


## Performing vector multiplication

In [ ]:
print(myVect * myVect)
print(np.multiply(myVect, myVect))

[ 1  4  9 16]
[ 1  4  9 16]


In [ ]:
print(myVect.dot(myVect))

30


## Understanding basic operations

In [ ]:
A = np.array([[1, 1], [1, 0]])
B = np.array([[1, 0], [0, 1]])
C = A - B

print(C)

[[ 0  1]
 [ 1 -1]]


In [ ]:
print(C * -2)

[[ 0 -2]
 [-2  2]]


## Performing matrix multiplication

In [ ]:
X = np.array([[4, 5], [2, 4], [3, 3]])
b = [3, -2]

print(np.dot(X, b))

[ 2 -2  3]


In [ ]:
B = np.array([[3, -2], [-2, 5]])

print(np.dot(X, B))

[[ 2 17]
 [-2 16]
 [ 3  9]]


## Glancing at advanced matrix operations

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
 print(np.linalg.inv(A))

[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


## Using vectorization effectively

In [38]:
y = np.array([44,21,37])
print (y)
print (y.shape)

[44 21 37]
(3,)


In [39]:
X = np.array([[1.1, 1, 545, 1],[4.6, 0, 345, 2],
              [7.2, 1, 754, 3]])
print (X)

[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]


In [42]:
X = np.array([1.1, 1, 545, 1, 4.6, 0, 345, 2,
              7.2, 1, 754, 3]).reshape(3,4)
print(X)

[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]


# Exploring the World of Probabilities

## Operating on probabilities

In [ ]:
Sixes = (1/6) * (1/6)
print(Sixes)

0.027777777777777776


In [ ]:
SixAndOther = (1/6) * (1 - (1/6))
print(SixAndOther)

0.1388888888888889


In [ ]:
OtherAndSix = (1/6) * (1 - (1/6))
print(OtherAndSix)

0.1388888888888889


In [ ]:
OneSix = (1/6) + (1/6)
print(OneSix)

0.3333333333333333


## Conditioning chance by Bayes’ theorem

In [ ]:
Female = 0.6 * 0.5 / 0.35
print(Female)

0.8571428571428572


In [ ]:
IsIll = 0.99 * 0.01 / ((0.01 * 0.99) + (0.99 * 0.01))
print(IsIll)

0.5
